.TH "StoerFisch-Core/include Directory Reference" 3 "StoerFisch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StoerFisch-Core/include Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBtelemetry_ring\&.cpp\fP"
.br
.RI "Implementierung des TelemetryRing-Producers (siehe \fBtelemetry_ring\&.hpp\fP für die vollständige Dokumentation von Layout und Ordering-Regeln)\&. "
.ti -1c
.RI "file \fBtelemetry_ring\&.hpp\fP"
.br
.RI "SPSC-Ringpuffer (Single-Producer/Single-Consumer) im POSIX Shared Memory, für den Telemetrie-/Event-Datenstrom C++ -> Python\&. "
.in -1c
