.TH "fisch::ActuatorStatePayload" 3 "StoerFisch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fisch::ActuatorStatePayload \- Payload für #6 (ActuatorState): Zustand des Jammers zum Zeitpunkt der Änderung -- Basis für die Tracking-Genauigkeit (Korrelation c) und die Leistungs-/Wirkungs-Kurve (Korrelation d)\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <telemetry_ring\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::uint32_t \fBactive_channel\fP"
.br
.ti -1c
.RI "float \fBtx_gain_db\fP"
.br
.ti -1c
.RI "std::uint32_t \fBpattern_id\fP"
.br
.ti -1c
.RI "std::uint8_t \fBenable\fP"
.br
.ti -1c
.RI "std::uint8_t \fBreserved\fP [3]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Payload für #6 (ActuatorState): Zustand des Jammers zum Zeitpunkt der Änderung -- Basis für die Tracking-Genauigkeit (Korrelation c) und die Leistungs-/Wirkungs-Kurve (Korrelation d)\&. 

\fCreserved\fP ist explizites Padding: ohne die 3 Byte würde der Compiler das Struct auf 16 Byte auffüllen, aber implizit -- das numpy-dtype müsste das exakt nachbilden\&. Explizit ist robuster als sich auf gleiches Compiler-Verhalten auf beiden Seiten zu verlassen\&. 
.PP
Definition at line \fB177\fP of file \fBtelemetry_ring\&.hpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "std::uint32_t fisch::ActuatorStatePayload::active_channel"

.PP
Definition at line \fB178\fP of file \fBtelemetry_ring\&.hpp\fP\&.
.SS "std::uint8_t fisch::ActuatorStatePayload::enable"

.PP
Definition at line \fB181\fP of file \fBtelemetry_ring\&.hpp\fP\&.
.SS "std::uint32_t fisch::ActuatorStatePayload::pattern_id"

.PP
Definition at line \fB180\fP of file \fBtelemetry_ring\&.hpp\fP\&.
.SS "std::uint8_t fisch::ActuatorStatePayload::reserved[3]"

.PP
Definition at line \fB182\fP of file \fBtelemetry_ring\&.hpp\fP\&.
.SS "float fisch::ActuatorStatePayload::tx_gain_db"

.PP
Definition at line \fB179\fP of file \fBtelemetry_ring\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for StoerFisch from the source code\&.
