.TH "fisch::RingHeader" 3 "StoerFisch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fisch::RingHeader \- Kopfdaten des Ringpuffers, liegen am Anfang des Shared-Memory- Segments\&. Enthält Metadaten zur Validierung sowie die Producer-/Consumer-Indizes\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <telemetry_ring\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::uint32_t \fBmagic\fP"
.br
.RI "muss kRingMagic sein "
.ti -1c
.RI "std::uint32_t \fBschema_version\fP"
.br
.RI "muss kSchemaVersion sein "
.ti -1c
.RI "std::uint64_t \fBcapacity_slots\fP"
.br
.RI "Anzahl Slots im Ring (2er Potenz pls) "
.ti -1c
.RI "std::atomic< std::uint64_t > \fBwrite_index\fP"
.br
.RI "nächster freier Slot (Producer) "
.ti -1c
.RI "std::atomic< std::uint64_t > \fBread_index\fP"
.br
.RI "nächster ungelesener Slot (Consumer) "
.ti -1c
.RI "std::atomic< std::uint64_t > \fBdropped_count\fP"
.br
.RI "von #8 geloggte Statistik "
.in -1c
.SH "Detailed Description"
.PP 
Kopfdaten des Ringpuffers, liegen am Anfang des Shared-Memory- Segments\&. Enthält Metadaten zur Validierung sowie die Producer-/Consumer-Indizes\&. 

write_index/read_index sind std::atomic, damit Producer und Consumer ohne Lock synchronisieren können (siehe Memory-Ordering-Hinweis oben)\&. Auf Python-Seite werden diese als schlichte, alignte uint64 gelesen -- auf x86-64 ist das Lesen eines einzelnen alignten 64-Bit-Worts atomar genug für diesen Zweck; das ist eine bewusste, dokumentierte Annahme\&. 
.PP
Definition at line \fB232\fP of file \fBtelemetry_ring\&.hpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "std::uint64_t fisch::RingHeader::capacity_slots"

.PP
Anzahl Slots im Ring (2er Potenz pls) 
.PP
Definition at line \fB235\fP of file \fBtelemetry_ring\&.hpp\fP\&.
.SS "std::atomic<std::uint64_t> fisch::RingHeader::dropped_count"

.PP
von #8 geloggte Statistik 
.PP
Definition at line \fB238\fP of file \fBtelemetry_ring\&.hpp\fP\&.
.SS "std::uint32_t fisch::RingHeader::magic"

.PP
muss kRingMagic sein 
.PP
Definition at line \fB233\fP of file \fBtelemetry_ring\&.hpp\fP\&.
.SS "std::atomic<std::uint64_t> fisch::RingHeader::read_index"

.PP
nächster ungelesener Slot (Consumer) 
.PP
Definition at line \fB237\fP of file \fBtelemetry_ring\&.hpp\fP\&.
.SS "std::uint32_t fisch::RingHeader::schema_version"

.PP
muss kSchemaVersion sein 
.PP
Definition at line \fB234\fP of file \fBtelemetry_ring\&.hpp\fP\&.
.SS "std::atomic<std::uint64_t> fisch::RingHeader::write_index"

.PP
nächster freier Slot (Producer) 
.PP
Definition at line \fB236\fP of file \fBtelemetry_ring\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for StoerFisch from the source code\&.
