.TH "fisch::DetectionEventPayload" 3 "StoerFisch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fisch::DetectionEventPayload \- Payload für #3 (DetectionEvent): einzelnes sporadisches Ereignis, z\&.B\&. 'Advertising auf CH37'\&. Zeitstempel liegt bereits im umgebenden \fBTelemetryRecord\fP, nicht nochmal hier\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <telemetry_ring\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::uint32_t \fBchannel\fP"
.br
.ti -1c
.RI "std::uint32_t \fBevent_kind\fP"
.br
.RI "0=AdvertisingPDU, 1=DataPDU, 2=Unknown "
.ti -1c
.RI "float \fBrssi_dbm\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Payload für #3 (DetectionEvent): einzelnes sporadisches Ereignis, z\&.B\&. 'Advertising auf CH37'\&. Zeitstempel liegt bereits im umgebenden \fBTelemetryRecord\fP, nicht nochmal hier\&. 
.PP
Definition at line \fB137\fP of file \fBtelemetry_ring\&.hpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "std::uint32_t fisch::DetectionEventPayload::channel"

.PP
Definition at line \fB138\fP of file \fBtelemetry_ring\&.hpp\fP\&.
.SS "std::uint32_t fisch::DetectionEventPayload::event_kind"

.PP
0=AdvertisingPDU, 1=DataPDU, 2=Unknown 
.PP
Definition at line \fB139\fP of file \fBtelemetry_ring\&.hpp\fP\&.
.SS "float fisch::DetectionEventPayload::rssi_dbm"

.PP
Definition at line \fB140\fP of file \fBtelemetry_ring\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for StoerFisch from the source code\&.
