.TH "fisch::LatencyTimestampsPayload" 3 "StoerFisch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fisch::LatencyTimestampsPayload \- Payload für #4 (LatencyTimestamps)\&. Alle Zeitstempel in Nanosekunden seit CLOCK_MONOTONIC, damit Drift durch Systemzeit-Sprünge ausgeschlossen ist\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <telemetry_ring\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::uint64_t \fBt1adc_ns\fP"
.br
.RI "Sample-Ankunft an ADC / SDR-Callback\&. "
.ti -1c
.RI "std::uint64_t \fBt2_fft_done_ns\fP"
.br
.RI "FFT-Verarbeitung abgeschlossen\&. "
.ti -1c
.RI "std::uint64_t \fBt3_decision_ns\fP"
.br
.RI "Regler Entscheidung getroffen\&. "
.ti -1c
.RI "std::uint64_t \fBt4_dac_out_ns\fP"
.br
.RI "Stellsignal am DAC/TX ausgegeben\&. "
.in -1c
.SH "Detailed Description"
.PP 
Payload für #4 (LatencyTimestamps)\&. Alle Zeitstempel in Nanosekunden seit CLOCK_MONOTONIC, damit Drift durch Systemzeit-Sprünge ausgeschlossen ist\&. 
.PP
Definition at line \fB72\fP of file \fBtelemetry_ring\&.hpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "std::uint64_t fisch::LatencyTimestampsPayload::t1adc_ns"

.PP
Sample-Ankunft an ADC / SDR-Callback\&. 
.PP
Definition at line \fB73\fP of file \fBtelemetry_ring\&.hpp\fP\&.
.SS "std::uint64_t fisch::LatencyTimestampsPayload::t2_fft_done_ns"

.PP
FFT-Verarbeitung abgeschlossen\&. 
.PP
Definition at line \fB74\fP of file \fBtelemetry_ring\&.hpp\fP\&.
.SS "std::uint64_t fisch::LatencyTimestampsPayload::t3_decision_ns"

.PP
Regler Entscheidung getroffen\&. 
.PP
Definition at line \fB75\fP of file \fBtelemetry_ring\&.hpp\fP\&.
.SS "std::uint64_t fisch::LatencyTimestampsPayload::t4_dac_out_ns"

.PP
Stellsignal am DAC/TX ausgegeben\&. 
.PP
Definition at line \fB76\fP of file \fBtelemetry_ring\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for StoerFisch from the source code\&.
