.TH "fisch::BufferHealthPayload" 3 "StoerFisch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fisch::BufferHealthPayload \- Payload für #8 (BufferHealth): Validitätsprüfung der Messung\&. Wird gebraucht, um Latenz-Ausreißer als Messartefakt vs\&. echtes Reglerverhalten zu unterscheiden (siehe Korrelation e)\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <telemetry_ring\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::uint32_t \fBusb_overruns\fP"
.br
.ti -1c
.RI "std::uint32_t \fBusb_underruns\fP"
.br
.ti -1c
.RI "std::uint32_t \fBdropped_samples\fP"
.br
.ti -1c
.RI "float \fBactual_sample_rate_hz\fP"
.br
.ti -1c
.RI "std::uint8_t \fBpll_locked\fP"
.br
.RI "0/1 als uint8_t für stabile Byte Größe "
.in -1c
.SH "Detailed Description"
.PP 
Payload für #8 (BufferHealth): Validitätsprüfung der Messung\&. Wird gebraucht, um Latenz-Ausreißer als Messartefakt vs\&. echtes Reglerverhalten zu unterscheiden (siehe Korrelation e)\&. 
.PP
Definition at line \fB101\fP of file \fBtelemetry_ring\&.hpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "float fisch::BufferHealthPayload::actual_sample_rate_hz"

.PP
Definition at line \fB105\fP of file \fBtelemetry_ring\&.hpp\fP\&.
.SS "std::uint32_t fisch::BufferHealthPayload::dropped_samples"

.PP
Definition at line \fB104\fP of file \fBtelemetry_ring\&.hpp\fP\&.
.SS "std::uint8_t fisch::BufferHealthPayload::pll_locked"

.PP
0/1 als uint8_t für stabile Byte Größe 
.PP
Definition at line \fB106\fP of file \fBtelemetry_ring\&.hpp\fP\&.
.SS "std::uint32_t fisch::BufferHealthPayload::usb_overruns"

.PP
Definition at line \fB102\fP of file \fBtelemetry_ring\&.hpp\fP\&.
.SS "std::uint32_t fisch::BufferHealthPayload::usb_underruns"

.PP
Definition at line \fB103\fP of file \fBtelemetry_ring\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for StoerFisch from the source code\&.
