.TH "main" 3 "StoerFisch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "main\&.main ()"

.PP
Definition at line \fB1\fP of file \fBmain\&.py\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for StoerFisch from the source code\&.
