.TH "StoerFisch-Core/include/telemetry_ring.cpp" 3 "StoerFisch" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StoerFisch-Core/include/telemetry_ring.cpp \- Implementierung des TelemetryRing-Producers (siehe \fBtelemetry_ring\&.hpp\fP für die vollständige Dokumentation von Layout und Ordering-Regeln)\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'telemetry_ring\&.hpp'\fP
.br
\fC#include <fcntl\&.h>\fP
.br
\fC#include <sys/mman\&.h>\fP
.br
\fC#include <sys/stat\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBfisch\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Implementierung des TelemetryRing-Producers (siehe \fBtelemetry_ring\&.hpp\fP für die vollständige Dokumentation von Layout und Ordering-Regeln)\&. 


.PP
Definition in file \fBtelemetry_ring\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for StoerFisch from the source code\&.
